name: spongechat
services:
  spongechat:
    image: "ghcr.io/spongedsc/spongechat:dev-v2"
    env_file:
      - ./.env
    environment:
      - KV_URI=redis://dragonfly:6379
    restart: on-failure
    depends_on:
      - dragonfly

  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    environment:
      - DFLY_snapshot_cron=*/30 * * * *
    volumes:
      - dragonflydata:/data
  wastebin:
    image: 'quxfoo/wastebin:latest'
    environment:
      - WASTEBIN_DATABASE_PATH=/data/state.db
    volumes:
      - wastebindata:/data
    ports:
      - "8088:8088"
    user: "0:0"

volumes:
  dragonflydata:
  wastebindata:
