name: pathways
services:
  pathways:
    image: "ghcr.io/spongedsc/pathways:latest"
    env_file:
      - ./.env
    environment:
      - KV_URI=redis://dragonfly:6379
    restart: on-failure
    depends_on:
      - dragonfly

  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    ulimits:
      memlock: -1
    environment:
      - DFLY_snapshot_cron=*/30 * * * *
    volumes:
      - dragonflydata:/data

volumes:
  dragonflydata:
