name: spongechat
services:
  spongechat:
    image: "ghcr.io/spongedsc/spongechat:dev-v2"
    env_file:
      - ./.env
    environment:
      - KV_URI=redis://dragonfly:6379
    restart: on-failure
    depends_on:
      - dragonfly

  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    volumes:
      - dragonflydata:/data

volumes:
  dragonflydata:
