name: Deploy Beta Docker Image to GHCR

on:
  push:
    branches:
      - beta
      - staging
  workflow_dispatch:

jobs:
      push-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Make repo lowercase'
            run: |
              echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
              
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@8530928916aaef40f59e6f221989ccb31f5759e7

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GH_TOKEN}}

          - name: 'Build & Publish Docker Image'
            run: |
              docker build . --tag "ghcr.io/${REPO}:beta"
              docker push "ghcr.io/${REPO}:beta"
