name: Prettier Linting

on:
  push:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actionsx/prettier@v2
      with:
        args: --check .
