name: Prettier Formatting

on:
  push:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actionsx/prettier@v3
        with:
          args: --check .
